nginx:
  build: ./nginx
  volumes_from:
    - datastore  
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - "80:80"

fluentdproducer:
  build: ./fluentd 
  volumes_from:
    - datastore
  volumes:
    - ./fluentd/producer-td-agent.conf:/etc/td-agent/td-agent.conf
  volumes_from:
    - datastore
  environment:
    STREAM_NAME: --------------------
    AWS_KEY_ID:  --------------------
    AWS_SEC_KEY: --------------------
    REGION:      --------------------

fluentdconsumer:
  build: ./fluentd
  volumes_from:
    - datastore
  volumes:
    - ./fluentd/consumer-td-agent.conf:/etc/td-agent/td-agent.conf
  volumes_from:
    - datastore
  environment:
    STREAM_NAME: -------------------- 
    AWS_KEY_ID:  --------------------
    AWS_SEC_KEY: --------------------
    REGION:      --------------------

datastore:
  build: ./datastore
  volumes:
    - /var/log/nginx
  command: mkdir /var/log/nginx
